"""empty message

Revision ID: 68a51306c0b7
Revises: 12083c51883c
Create Date: 2019-10-27 06:35:27.947429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a51306c0b7'
down_revision = '12083c51883c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###
