"""empty message

Revision ID: 6bce1dd2112f
Revises: d88fd6930ac0
Create Date: 2019-10-27 19:33:58.378334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bce1dd2112f'
down_revision = 'd88fd6930ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_comment_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_comment_id_fkey', 'blogs', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###
