"""empty message

Revision ID: 7e952a791ec1
Revises: bb3d6f15174a
Create Date: 2019-10-27 08:06:46.099721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e952a791ec1'
down_revision = 'bb3d6f15174a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_comment_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    op.add_column('comment', sa.Column('blogs_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'blogs', ['blogs_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'blogs_id')
    op.add_column('blogs', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_comment_id_fkey', 'blogs', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###
