"""empty message

Revision ID: 8bdeb2db6623
Revises: 7e952a791ec1
Create Date: 2019-10-27 08:22:05.223237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdeb2db6623'
down_revision = '7e952a791ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'comment', ['comment_id'], ['id'])
    op.drop_constraint('comment_blogs_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'blogs_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('blogs_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_blogs_id_fkey', 'comment', 'blogs', ['blogs_id'], ['id'])
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    # ### end Alembic commands ###
