"""empty message

Revision ID: 962e67bdd6ce
Revises: c8f776f451b7
Create Date: 2019-10-29 20:52:34.922025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962e67bdd6ce'
down_revision = 'c8f776f451b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
