"""empty message

Revision ID: ad7b4a5c2a2f
Revises: cb39983757aa
Create Date: 2019-10-27 19:26:56.571784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7b4a5c2a2f'
down_revision = 'cb39983757aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
