"""empty message

Revision ID: bb3d6f15174a
Revises: c1b709a28149
Create Date: 2019-10-27 08:04:23.566873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3d6f15174a'
down_revision = 'c1b709a28149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_blogs_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'blogs_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('blogs_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_blogs_id_fkey', 'comment', 'blogs', ['blogs_id'], ['id'])
    # ### end Alembic commands ###
