"""empty message

Revision ID: cb39983757aa
Revises: dbc00468ae34
Create Date: 2019-10-27 19:25:43.153533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb39983757aa'
down_revision = 'dbc00468ae34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'comment', ['comment_id'], ['id'])
    op.add_column('users', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'comment_id')
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    # ### end Alembic commands ###
