"""empty message

Revision ID: d7b0624903ac
Revises: 9e446d7fc356
Create Date: 2019-10-27 20:12:03.624751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b0624903ac'
down_revision = '9e446d7fc356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.String(length=255), nullable=True))
    op.drop_column('comment', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###
